import { assetVersion, imageDomainUrl } from 'shared/constants/Assets';

export const SOULSCAPE_IMAGES = {
  'h-bg': {
    url: `${imageDomainUrl}/Soulscape/h-bg.jpg?v=${assetVersion}`,
    width: 2560,
    height: 1440,
    alt: 'image',
  },
  'h-phone-1': {
    url: `${imageDomainUrl}/Soulscape/h-phone-1.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  'h-phone-2': {
    url: `${imageDomainUrl}/Soulscape/h-phone-2.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  'h-phone-3': {
    url: `${imageDomainUrl}/Soulscape/h-phone-3.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's1-phone-1': {
    url: `${imageDomainUrl}/Soulscape/s1-phone-1.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's1-phone-2': {
    url: `${imageDomainUrl}/Soulscape/s1-phone-2.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's1-phone-3': {
    url: `${imageDomainUrl}/Soulscape/s1-phone-3.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's2-phone-1': {
    url: `${imageDomainUrl}/Soulscape/s2-phone-1.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's2-phone-2': {
    url: `${imageDomainUrl}/Soulscape/s2-phone-2.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's3-phone-1': {
    url: `${imageDomainUrl}/Soulscape/s3-phone-1.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's3-phone-2': {
    url: `${imageDomainUrl}/Soulscape/s3-phone-2.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's3-phone-3': {
    url: `${imageDomainUrl}/Soulscape/s3-phone-3.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's3-phone-4': {
    url: `${imageDomainUrl}/Soulscape/s3-phone-4.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's4-phone-1': {
    url: `${imageDomainUrl}/Soulscape/s4-phone-1.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's4-phone-2': {
    url: `${imageDomainUrl}/Soulscape/s4-phone-2.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's4-phone-3': {
    url: `${imageDomainUrl}/Soulscape/s4-phone-3.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's5-phone-1': {
    url: `${imageDomainUrl}/Soulscape/s5-phone-1.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's5-phone-2': {
    url: `${imageDomainUrl}/Soulscape/s5-phone-2.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's5-phone-3': {
    url: `${imageDomainUrl}/Soulscape/s5-phone-3.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's6-bg': {
    url: `${imageDomainUrl}/Soulscape/s6-bg.jpg?v=${assetVersion}`,
    width: 2559,
    height: 821,
    alt: 'image',
  },
  's6-phone-1': {
    url: `${imageDomainUrl}/Soulscape/s6-phone-1.webp?v=${assetVersion}`,
    width: 978,
    height: 1997,
    alt: 'image',
  },
  's6-phone-2': {
    url: `${imageDomainUrl}/Soulscape/s6-phone-2.webp?v=${assetVersion}`,
    width: 963,
    height: 1584,
    alt: 'image',
  },
};
